import type { TestPlan, Execution, ActivityItem } from "./home.types";

export const MOCK_TEST_PLANS: TestPlan[] = [
  {
    id: "tp-001",
    name: "Checkout Flow E2E",
    modality: "web",
    framework: "Playwright",
    status: "approved",
    scenarioCount: 24,
    passRate: 96,
    lastUpdated: "2h ago",
    health: "healthy",
  },
  {
    id: "tp-002",
    name: "Payment Gateway API",
    modality: "api",
    framework: "Karate",
    status: "review",
    scenarioCount: 18,
    passRate: 88,
    lastUpdated: "45m ago",
    health: "degrading",
  },
  {
    id: "tp-003",
    name: "Product Search & Filters",
    modality: "web",
    framework: "Cypress",
    status: "generating",
    scenarioCount: 12,
    passRate: null,
    lastUpdated: "12m ago",
    health: null,
  },
  {
    id: "tp-004",
    name: "User Authentication",
    modality: "web",
    framework: "Playwright",
    status: "draft",
    scenarioCount: 8,
    passRate: 91,
    lastUpdated: "1d ago",
    health: "healthy",
  },
  {
    id: "tp-005",
    name: "Order Management API",
    modality: "api",
    framework: "Karate",
    status: "approved",
    scenarioCount: 31,
    passRate: 99,
    lastUpdated: "3h ago",
    health: "healthy",
  },
  {
    id: "tp-006",
    name: "Mobile App Login",
    modality: "ios",
    framework: "XCTest",
    status: "draft",
    scenarioCount: 6,
    passRate: null,
    lastUpdated: "2d ago",
    health: null,
  },
];

export const MOCK_EXECUTIONS: Execution[] = [
  {
    id: "ex-001",
    date: "Today 14:32",
    env: "PRE",
    status: "passed",
    passRate: 96,
    duration: "4m 12s",
    trigger: "manual",
  },
  {
    id: "ex-002",
    date: "Today 09:15",
    env: "PRE",
    status: "failed",
    passRate: 88,
    duration: "3m 58s",
    trigger: "cron",
  },
  {
    id: "ex-003",
    date: "Yesterday 22:00",
    env: "PRO",
    status: "passed",
    passRate: 100,
    duration: "4m 45s",
    trigger: "cron",
  },
  {
    id: "ex-004",
    date: "Yesterday 14:00",
    env: "DEV",
    status: "passed",
    passRate: 92,
    duration: "3m 30s",
    trigger: "webhook",
  },
  {
    id: "ex-005",
    date: "Jun 2 09:00",
    env: "PRE",
    status: "failed",
    passRate: 83,
    duration: "4m 01s",
    trigger: "cron",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    text: "Checkout Flow E2E passed on PRE",
    time: "2h ago",
    status: "success",
  },
  {
    text: "Product Search & Filters generating…",
    time: "12m ago",
    status: "info",
  },
  {
    text: "Payment Gateway API needs review",
    time: "45m ago",
    status: "warning",
  },
  {
    text: "Order Management API approved by Elena",
    time: "3h ago",
    status: "success",
  },
  {
    text: "Payment Gateway pass rate below 90%",
    time: "1h ago",
    status: "error",
  },
  {
    text: "AI suggested 3 new test cases for Auth",
    time: "4h ago",
    status: "info",
  },
];
